"""empty message

Revision ID: 0ed0e32a88de
Revises: 566d72a03529
Create Date: 2025-03-20 01:59:44.616864

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0ed0e32a88de'
down_revision = '566d72a03529'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inbox', schema=None) as batch_op:
        batch_op.alter_column('estimated_amount',
               existing_type=mysql.FLOAT(),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inbox', schema=None) as batch_op:
        batch_op.alter_column('estimated_amount',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=mysql.FLOAT(),
               existing_nullable=True)

    # ### end Alembic commands ###
