"""empty message

Revision ID: 566d72a03529
Revises: f89875e27642
Create Date: 2025-03-20 01:52:40.061437

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '566d72a03529'
down_revision = 'f89875e27642'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('machine_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('lifespan', sa.Integer(), nullable=False),
    sa.Column('image', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('machine_parts_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('machine_info_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('lifespan', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['machine_info_id'], ['machine_info.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('inbox', schema=None) as batch_op:
        batch_op.add_column(sa.Column('machine_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('estimated_amount', sa.Float(), nullable=True))

    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('machine_name', sa.String(length=150), nullable=False))
        batch_op.add_column(sa.Column('estimated_amount', sa.Float(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.drop_column('estimated_amount')
        batch_op.drop_column('machine_name')

    with op.batch_alter_table('inbox', schema=None) as batch_op:
        batch_op.drop_column('estimated_amount')
        batch_op.drop_column('machine_name')

    op.drop_table('machine_parts_info')
    op.drop_table('machine_info')
    # ### end Alembic commands ###
