"""empty message

Revision ID: 918662aa9d1c
Revises: 42cfb53ebdec
Create Date: 2025-03-20 20:11:45.670589

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '918662aa9d1c'
down_revision = '42cfb53ebdec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inbox', schema=None) as batch_op:
        batch_op.add_column(sa.Column('receiver_name', sa.String(length=100), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inbox', schema=None) as batch_op:
        batch_op.drop_column('receiver_name')

    # ### end Alembic commands ###
