"""empty message

Revision ID: 971595234412
Revises: cef96ce5d8c1
Create Date: 2025-03-19 14:10:06.025055

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '971595234412'
down_revision = 'cef96ce5d8c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('machines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('purchase_date', sa.Date(), nullable=False),
    sa.Column('lifespan', sa.Integer(), nullable=False),
    sa.Column('image', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('parts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('machine_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('purchase_date', sa.Date(), nullable=False),
    sa.Column('lifespan', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['machine_id'], ['machines.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('parts')
    op.drop_table('machines')
    # ### end Alembic commands ###
