"""empty message

Revision ID: cef96ce5d8c1
Revises: b7a3ed126215
Create Date: 2025-03-18 23:14:44.100897

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cef96ce5d8c1'
down_revision = 'b7a3ed126215'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inbox', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location', sa.String(length=100), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inbox', schema=None) as batch_op:
        batch_op.drop_column('location')

    # ### end Alembic commands ###
