"""empty message

Revision ID: eb7dea548125
Revises: 
Create Date: 2025-08-25 20:40:57.835672

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb7dea548125'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('inbox',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sender_name', sa.String(length=100), nullable=False),
    sa.Column('receiver_name', sa.String(length=100), nullable=False),
    sa.Column('text', sa.String(length=255), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('time', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('unread', sa.Boolean(), nullable=True),
    sa.Column('location', sa.String(length=100), nullable=False),
    sa.Column('payment_confirmation', sa.Boolean(), nullable=True),
    sa.Column('machine_name', sa.String(length=100), nullable=True),
    sa.Column('estimated_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inventory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_name', sa.String(length=255), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('login',
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=100), nullable=False),
    sa.Column('phone_no', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('machine_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('lifespan', sa.Integer(), nullable=False),
    sa.Column('image', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('machines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('purchase_date', sa.Date(), nullable=False),
    sa.Column('lifespan', sa.Integer(), nullable=False),
    sa.Column('image', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('transaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transaction_id', sa.String(length=100), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('machine_name', sa.String(length=150), nullable=False),
    sa.Column('estimated_amount', sa.Float(), nullable=False),
    sa.Column('account', sa.String(length=100), nullable=False),
    sa.Column('location', sa.String(length=100), nullable=False),
    sa.Column('read', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('transaction_id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('phone_no', sa.String(length=20), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone_no'),
    sa.UniqueConstraint('username')
    )
    op.create_table('machine_parts_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('machine_info_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('lifespan', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['machine_info_id'], ['machine_info.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('machine_services',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('machine_id', sa.Integer(), nullable=False),
    sa.Column('last_service', sa.Date(), nullable=False),
    sa.Column('next_service', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['machine_id'], ['machines.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('parts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('machine_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('purchase_date', sa.Date(), nullable=False),
    sa.Column('lifespan', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['machine_id'], ['machines.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('parts')
    op.drop_table('machine_services')
    op.drop_table('machine_parts_info')
    op.drop_table('user')
    op.drop_table('transaction')
    op.drop_table('machines')
    op.drop_table('machine_info')
    op.drop_table('login')
    op.drop_table('inventory')
    op.drop_table('inbox')
    op.drop_table('admin')
    # ### end Alembic commands ###
